dataset_name: anet_v2
# train_split: ['train']
# val_split: ['test']
train_split: ['training']
val_split: ['testing']
round: 1000
active_learning_method: uniform # dummy name
dataset: {
  json_file: /data3/xiaodan8/Activitynet/anet1.3_i3d_filtered.json, # anet_win128_int32 anet_win256_int16
  feat_folder: /data3/xiaodan8/Activitynet/I3D,
  file_prefix: v_,
  file_ext: .npy,
  num_classes: 200,
  input_dim: 2048,
  feat_stride: 32, # 128 8,
  num_frames: 16, # 16,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 288 # 9216, # 576*18
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  n_mha_win_size: [7, 7, 7, 7, 7, -1], # [7, 7, 7, 7, 7, -1]  [7, 7, 7, -1]
  # n_mha_win_size: 19,
}
opt: {
  learning_rate: 0.001, # 0.000375 CLIP: 0.0001 VIT: 0.001 vivit: 0.0001
  epochs: 35,
  weight_decay: 0.05,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,
}
output_folder: ./ckpt/
